### Users create (signup)

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "SuzzyQ",
  "email": "suzzy@q.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "suzzy@q.com",
  "password": "password"
}

### Users show

GET http://localhost:3000/users/2
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMzMjM0MTd9.kZu5YC9bzvnXviSAp5DV2oTh8PrT5e9aOIppAAlDP68